#!/usr/bin/env bash
#configuration of my domain zone so that the subdomain www points to my load-balancer IP (lb-01).

function get_record_type {
    local record_type=$(echo"$1" | awk '{print $4}')
    echo "$record_type"
}

function get_destination {
    local destination=$(echo "$1" | awk '{print $5}')
    echo "$destination"
}

domain="$1"
subdomain="$2"

if [[ -z "$subdomain" ]]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    subdomains=("$subdomain")
fi
for subdomain in "${subdomains[@]}"; do 
    record="$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')"
    record_type=$(get_record_type "$record")
    destination=$(dig +short "$sub.$domain" | awk '{print $1}')

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
done
