#!/usr/bin/env bash
#configuration of my domain zone so that the subdomain www points to my load-balancer IP (lb-01).

if [ $# == 2 ]; then
    domain=$1
    subdomain=$2
    subdomains=$subdomain
else
    domain=$1
    subdomains=("www" "lb-01" "web-01" "web-02")
fi

for sub in ${subdomains[@]}; do
    record_type="$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')"
    destination=$(dig +short "$sub.$domain" | awk '{print $1}')
    echo "The subdomain $sub is a $record_type record and points to $destination"

done